version: "3.8"

services:
  app:
    image: ghcr.io/hadesrofl/flashcards:latest
    restart: on-failure:10
    env_file:
      - .env
    ports:
      - 3000:${PORT}
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:latest
    restart: on-failure
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 3s
      start_period: 15s
      retries: 3
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
