version: "3.8"

services:
  app:
    image: ghcr.io/hadesrofl/flashcards:latest
    restart: on-failure:10
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      HOSTNAME: ${HOSTNAME}
      PORT: ${PORT}
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - 3000:${PORT}
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:latest
    restart: on-failure
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 3s
      start_period: 15s
      retries: 3
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
